name: Analyze PR

on:
  workflow_run:
    workflows:
      - 'Build'
    types:
      - completed

permissions:
  pull-requests: read
  contents: read
  checks: write

jobs:
  analyze:
    name: Analyze Code
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_repository.fork
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          cat << EOF
          ${{ toJson(github.event) }}
          EOF

      - name: Checkout base
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          path: base

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          # for Sonar
          fetch-depth: 0

      - name: Get analysis data
        uses: ./base/.github/actions/prepare-analysis

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: temurin

      - name: Run SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          cp -f base/pom.xml .
          mvn -B \
          -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }} \
          -Dsonar.pullrequest.key=${{ github.event.workflow_run.pull_requests[0].number }} \
          -Dsonar.pullrequest.branch=${{ github.event.workflow_run.pull_requests[0].head.ref }} \
          -Dsonar.pullrequest.base=${{ github.event.workflow_run.pull_requests[0].base.ref }} \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
