name: pr-build

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # for Sonar
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          architecture: x64
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn verify -B -"Dgpg.skip"

      - name: Save PR number to file
        run: echo ${{ github.event.number }} > pr_number.txt

      - name: Archive PR number
        uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr_number.txt

      - name: Archive JaCoCo
        uses: actions/upload-artifact@v3
        with:
          name: jacoco
          path: target/jacoco.exec
